/*
* generated by Xtext
*/
package ch.miranet.dsl.site.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SiteDSLProposalProvider extends AbstractSiteDslProposalProvider {

}
