/*
* generated by Xtext
*/
package ch.miranet.dsl.site.ui.contentassist;

import ch.miranet.dsl.site.ui.contentassist.AbstractSiteDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SiteDslProposalProvider extends AbstractSiteDslProposalProvider {

}
