/*
 * generated by Xtext
 */
package ch.miranet.dsl.site.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SiteDslUiModule extends ch.miranet.dsl.site.ui.AbstractSiteDslUiModule {
	public SiteDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
