/*
 * generated by Xtext
 */
package ch.miranet.dsl.site;

import org.eclipse.xtext.conversion.IValueConverterService;

import ch.miranet.dsl.site.converter.SiteDslValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SiteDslRuntimeModule extends ch.miranet.dsl.site.AbstractSiteDslRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return SiteDslValueConverterService.class;
	}
	
}
