/*
* generated by Xtext
*/
package ch.miranet.dsl.site.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class SiteDSLTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
